### ISSUE TITLE
This game sucks

### ISSUE THREAD

**Issue by Jumpshawt** [Spillw4y/TRUGame#2]
seriously this game sucks, i have never seen a game that has less content and is less of a fucking game holy shit go back to godot you fucking loser you're a bad programmer and not even the fucking godette motherfucker would want you to be using their shitty game engine. argent was only a mid high tier game and the pixel art was low, not even mid. zombies game was a great experience however it made eye contact with you so it instantly got ever std known to man. you are ever std known to man elias, just freaking horrible. i don't even know what to type anymore my fingers are gonna get rage induced arthritus at the rate i'm going. i would love to lie but you're e-lie-ass looking motherfucker elias. in many ways the birth of elias can be compared to the birth of the antichrist and the endo of the world, oh shit its the of the AAAAAAAAAAAAAA

**Comment by Spillw4y** [comment]
L + Ratio

**Comment by Jumpshawt** [comment]
argent was mid

**Comment by Jumpshawt** [comment]
cry about it

**Comment by Spillw4y** [comment]
Youve made your final mistake

**Comment by Jumpshawt** [comment]
it was low c tier

**Comment by Spillw4y** [comment]
every minute your not running im getting closer

**Comment by Jumpshawt** [comment]
1 off from bottom
